# Generated by Django 3.1.7 on 2021-03-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soils', '0002_soilmakeup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soil',
            name='dose_of_lime_or_cement',
            field=models.CharField(max_length=30),
        ),
    ]
