# Generated by Django 3.1.7 on 2021-03-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='soil_sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lime_or_cement_stabilization', models.CharField(max_length=240, verbose_name='Name')),
                ('dose_of_lime_or_cement', models.CharField(max_length=30)),
            ],
        ),
    ]
