# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main, garrett, WebUI-main ]
  pull_request:
    branches: [ main, garrett, WebUI-main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Run build.sh
      run: |
        chmod +x ./build.sh
        ./build.sh
    - name: Run clean.sh
      run: |
        chmod +x ./clean.sh
        ./clean.sh
        
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        python-version: 3.9
    - name: Run test.sh
      run: |
        chmod +x ./test.sh
        ./test.sh
